name: Hello world workflow
on:
  push:
    branches: 
      - main
  pull_requests:
    branches:
      -main
  workflow_dispatch:

  jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 
        - name: hello-world
          run: echo "heloow world"
          shell: bash
    goodbye:
      runs-on: ubuntu-latest
      steps:
        - name: goobyeworld
          run: echo "goodbyeworld"
          shell: bash
