name: Hello world workflow
on:
  push
#   issues:
#     types:
#       - opened
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
     - name: dump github actions
       run: echo '${{ toJSON(github.event) }}'
