name: Hello world workflow
on:
  issue_types:
    - opened
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
     - name: dump github actions
       run: echo '${{ toJSON(github.event) }}' | jq
       shell: bash
  
