name: practice
on: 
  push: 
    branches: 
      - main
jobs: 
  job1:
    runs-on: ubuntu-latest 
    steps:
        - uses: actions/checkout@v2
        - run: mkdir -p refs/heads/main/pavan
        - run: echo hello > refs/heads/main/pavan/world.txt
        - uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: refs/heads/main/pavan/world.txt
  job2:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/download-artifact@v2
          with: 
            name: my-artifact
      
